remote_theme: jekyll/minima

minima:
  skin: dark

author:
  name: Captain
  email: "captain8771pog+gh@gmail.com"

disqus:
  shortname: captain8771

url: "https://captain8771.github.io"

header_pages:
  - info/about.md